# Generated by Django 2.2.4 on 2019-08-16 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('', 'Select Option'), ('1', 'Male'), ('2', 'Female')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(blank=True, max_length=10, null=True)),
                ('organization', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=50)),
                ('md5', models.CharField(max_length=100)),
            ],
        ),
    ]
