# Generated by Django 2.2.4 on 2019-08-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='adduser',
            table='add_user',
        ),
    ]
