# Generated by Django 2.1.5 on 2019-04-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('bank_name', models.CharField(max_length=20)),
                ('ac_holder_name', models.CharField(max_length=70)),
                ('ac_type', models.CharField(max_length=15)),
                ('ac_number', models.CharField(max_length=26)),
                ('ifsc_code', models.CharField(max_length=14)),
                ('branch', models.CharField(max_length=30)),
                ('gst_number', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'bank_details',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tickets_Sale',
            fields=[
                ('table_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('ticket_id', models.IntegerField()),
                ('booking_id', models.IntegerField()),
                ('organizer', models.IntegerField()),
                ('ticket_type', models.CharField(max_length=100)),
                ('purchase_date', models.DateTimeField()),
                ('ampunt_paid', models.CharField(max_length=8)),
                ('qty', models.IntegerField()),
                ('attendee_name', models.CharField(max_length=30)),
                ('attendee_contact', models.CharField(max_length=12)),
                ('attendee_email', models.CharField(max_length=80)),
                ('seller_site', models.CharField(max_length=80)),
                ('recieval_status', models.IntegerField(blank=True, null=True)),
                ('forward_status', models.IntegerField(blank=True, null=True)),
                ('ticket_handover', models.IntegerField()),
            ],
            options={
                'db_table': 'tickets_sale',
                'managed': False,
            },
        ),
    ]
