# Generated by Django 2.1.5 on 2019-04-18 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_bankdetails_tickets_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('fname', models.CharField(max_length=20)),
                ('lname', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=20)),
                ('password', models.CharField(blank=True, max_length=300, null=True)),
                ('admin_type', models.IntegerField()),
                ('admin_active', models.IntegerField()),
                ('team', models.IntegerField()),
                ('mobile', models.CharField(max_length=11)),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
    ]
