# Generated by Django 2.1.5 on 2019-04-18 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Event_Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.IntegerField()),
                ('admin_id', models.IntegerField()),
                ('super_admin_id', models.IntegerField()),
                ('event_id', models.IntegerField()),
                ('assignment_timestamp', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
            ],
            options={
                'db_table': 'admin_event_assignment',
                'managed': False,
            },
        ),
    ]
