# Generated by Django 2.1.7 on 2019-07-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_auto_20190421_0222'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAccess',
            fields=[
                ('access_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField()),
                ('updated_on', models.DateTimeField()),
                ('access_type', models.CharField(max_length=100)),
                ('read_access', models.IntegerField()),
                ('write_access', models.IntegerField()),
                ('delete_access', models.IntegerField()),
            ],
            options={
                'db_table': 'admin_accesses',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminAccessTypes',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
                ('updated_on', models.DateTimeField()),
                ('parameter', models.CharField(max_length=120)),
                ('details', models.TextField()),
            ],
            options={
                'db_table': 'admin_access_types',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
                ('admin_id', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
                ('parameter', models.CharField(max_length=150)),
                ('event_id', models.IntegerField()),
                ('action_taken', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'admin_action_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoostEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.TextField()),
                ('city2', models.TextField()),
                ('city3', models.TextField()),
                ('city4', models.TextField()),
            ],
            options={
                'db_table': 'BoostEvent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventEditLogs',
            fields=[
                ('table_id', models.IntegerField(primary_key=True, serialize=False)),
                ('event_id', models.IntegerField()),
                ('last_updated', models.DateTimeField()),
                ('parameter', models.CharField(max_length=350)),
                ('taken_action', models.CharField(max_length=350)),
                ('old_data', models.CharField(max_length=350)),
                ('new_data', models.CharField(max_length=350)),
                ('role', models.CharField(max_length=350)),
                ('user_id', models.IntegerField()),
            ],
            options={
                'db_table': 'event_edit_logs',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventProcesses',
            fields=[
                ('process_id', models.IntegerField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField()),
                ('process_type', models.CharField(max_length=100)),
                ('what_to_process', models.CharField(max_length=100)),
                ('msg_to_org', models.TextField()),
                ('active', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'event_processes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EventVerificationResult',
            fields=[
                ('event_id', models.IntegerField()),
                ('result_id', models.IntegerField(primary_key=True, serialize=False)),
                ('verified_at', models.DateTimeField()),
                ('verified_against', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'event_verification_result',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Payment_settlement',
            fields=[
                ('settlement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_added', models.DateTimeField()),
                ('date_modified', models.DateTimeField()),
                ('booking_id', models.CharField(max_length=50)),
                ('ticket_sale_id', models.CharField(max_length=50)),
                ('added_by', models.CharField(max_length=11)),
                ('modified_by', models.CharField(max_length=11)),
                ('receival_status', models.CharField(max_length=50)),
                ('expected_amnt_partner', models.CharField(max_length=11)),
                ('rcvd_amnt_partner', models.CharField(max_length=11)),
                ('receival_date', models.DateTimeField()),
                ('receival_invoice', models.CharField(max_length=300)),
                ('partner_dispute', models.TextField()),
                ('process_status', models.CharField(max_length=50)),
                ('amount_processed', models.CharField(max_length=11)),
                ('amount_process_date', models.DateTimeField()),
                ('process_invoice', models.CharField(max_length=300)),
                ('organizer_dispute', models.TextField()),
            ],
            options={
                'db_table': 'payment_settlement',
                'managed': False,
            },
        ),
    ]
