# Generated by Django 2.1.7 on 2019-07-27 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_adminaccess_adminaccesstypes_adminactionlog_boostevent_eventeditlogs_eventprocesses_eventverificatio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boostevent',
            options={'managed': True},
        ),
    ]
