# Generated by Django 2.1.7 on 2019-07-27 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20190727_0800'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boostevent',
            options={'managed': True},
        ),
    ]
