# Generated by Django 2.1.5 on 2019-04-17 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ercesscorp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_userid', models.TextField(blank=True, null=True)),
                ('md5', models.CharField(max_length=300)),
                ('firstname', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=40)),
                ('profile_pic', models.TextField()),
                ('gender', models.CharField(max_length=8)),
                ('location', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=11)),
                ('password', models.CharField(blank=True, max_length=300, null=True)),
                ('mobile_verified', models.IntegerField(default=0)),
                ('status', models.CharField(default='pending', max_length=8)),
                ('first_time', models.CharField(max_length=10)),
                ('organization_name', models.CharField(max_length=200)),
                ('organization_location', models.TextField()),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
    ]
