# Generated by Django 2.1.7 on 2019-07-27 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ercesscorp', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistrationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email_token', models.CharField(default='', max_length=250)),
                ('user_email_token_created_on', models.DateTimeField(blank=True, null=True)),
                ('user_password_token', models.CharField(default='', max_length=250)),
                ('user_email', models.CharField(default='', max_length=250)),
                ('user_password_token_created_on', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
